"""message

Revision ID: b2dedee8eae3
Revises: 5701e536c2dd
Create Date: 2024-04-23 15:24:27.396750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dedee8eae3'
down_revision = '5701e536c2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
